# Este docker-compose.yml é um exemplo de como configurar o painel do AVA para desenvolvimento local.
services:

  cache:
    image: redis:7.2-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      # init settings, executed only on deploy
      - "./src/postgres/:/docker-entrypoint-initdb.d"
      # database data
      - "~/projetos/IFRN/ava/volumes/db_data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  app:
    image: ctezlifrn/avapainel:1.1.0
    build:
      context: ./src
      # additional_contexts:
      #   django-adminlte3: ../django-adminlte3
    ports:
      - 80:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme

      - DJANGO_DEBUG=true
      - DJANGO_ALLOWED_HOSTS=ava,localhost

      # 1. Crie uma chave, em qualquer ferramenta, de no mímino 50 caracteres
      - DJANGO_SECRET_KEY=changeme

      # 2. Crie um project no Sentr.io e pegue a DNS
      # SENTRY_DNS=https://key@id.ingest.sentry.io/id

      # 3. Crie uma "Aplicações OAUTH2" no SUAP e pegue o client_id e o client_secret
      - SUAP_OAUTH_CLIENT_ID=changeme
      - SUAP_OAUTH_CLIENT_SECRET=changeme
      - SUAP_OAUTH_BASE_URL=https://suap.ifrn.edu.br
      - SUAP_OAUTH_REDIRECT_URI=http://ava/painel/authenticate/

      # 4. Crie uma aplicação oAuth2 no SUAP e pegue o client_id e o client_secret
      - SUAP_INTEGRADOR_KEY=changeme

      # 5. Se cadastre no https://userway.org/ e registre o token da conta
      - SHOW_USERWAY=True
      - USERWAY_ACCOUNT=changeme

      - SHOW_VLIBRAS=True

    volumes:
      # - '../django-adminlte3:/apps/django-adminlte3'
      - './src:/apps/app'
      - '~/projetos/IFRN/ava/volumes/painel_media:/var/media'
      - '~/projetos/IFRN/ava/volumes/painel_static:/var/static'
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
