services:

  cache:
    image: redis:7.0.2-alpine
    env_file:
      - ./confs/enabled/cache.env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]      
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15.1-alpine
    env_file:
      - ./confs/enabled/db.env
    volumes:
      # init settings, executed only on deploy
      - "./src/postgres/:/docker-entrypoint-initdb.d"
      # database data
      - "./volumes/db_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - 80:80
    volumes:
      # confs
      - ./confs/enabled/nginx.conf:/etc/nginx/conf.d/default.conf

  portal:
    image: 'ctezlifrn/avaportal:1.0.34'
    build: src/python/portal
    ports:
      - 8000:8000
    env_file:
      - ./confs/enabled/db.env
      - ./confs/enabled/cache.env
      - ./confs/enabled/portal.env
    volumes:
      - './src/python/portal:/apps/app'
      - './volumes/portal_media:/var/media'
      - './volumes/portal_static:/var/static'
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent --fail http://ava/painel/health/ | grep 'Database: OK' || exit 1"]
    #   interval: 3s
    #   timeout: 1s
    #   start_period: 1s
    #   retries: 30

  # moodle:
  #   image: 'ctezlifrn/moodle:4.1.2-php8.1-015'
  #   env_file:
  #     - ./confs/enabled/db.env
  #     - ./confs/enabled/cache.env
  #     - ./confs/enabled/ava01.env
  #   volumes:
  #     # Configs
  #     # - '../moodle__image/src/php/config.php:/var/www/html/config.php'
  #     # Plugins
  #     - '../moodle__auth_suap:/var/www/html/auth/suap'
  #     - '../moodle__local_suap:/var/www/html/local/suap'
  #     - '../moodle__block_suapattendance:/var/www/html/blocks/suapattendance'
  #     - '../moodle__theme_maeve:/var/www/html/theme/maeve'
  #     # Data
  #     - './volumes/moodle_data:/var/moodledata'
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl --silent --fail http://ava/ | grep AVA_01 || exit 1"]
  #     interval: 3s
  #     timeout: 1s
  #     start_period: 1s
  #     retries: 30
